#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deviceData?mysql=true&characterEncoding=utf8&useSSL=false
    username: liang
    password: 123
    driver-class-name: com.mysql.jdbc.Driver